AuthenticPhoto/Models/OrderSummaryViewModel.cs
using AuthenticPhoto.Business.Abstract;
using AuthenticPhoto.Business.ProductTool;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace AuthenticPhoto.Models
{
    public class OrderSummaryViewModel:ViewModelWithTranslations
    {
        public AuthenticOrder Order { get; set; }

        public string InvoiceCountry { get; set; }

        public bool VatValid { get; set; }

        public decimal CalculateVAT(decimal totalPriceExclVatHandling, bool isTransport)
        {
            decimal vat = 0;
            if (!isTransport)
            {
                if(VatValid)
                {
                    string EuCountryCodes = ConfigurationManager.AppSettings["EUVatFreeCountryList"];
                    if (EuCountryCodes.Contains(InvoiceCountry))
                    {
                        return 0;
                    }
                }
                vat = Math.Round(totalPriceExclVatHandling * (decimal)0.21, 2);
            }            
            return vat;
        }
    }
}

AuthenticPhoto/Models/PriceDetailsViewModel.cs
using AuthenticPhoto.Business.Abstract;
using AuthenticPhoto.Business.ProductTool;

namespace AuthenticPhoto.Models
{
    public class PriceDetailsViewModel: ViewModelWithTranslations
    {
        public UploadedImage Image { get; set; }

        public string LanguageCode { get; set; }

        public string OrderID { get; set; }

        public enum PriceDetailsContext
        {
            Calculator, Order
        }

        public PriceDetailsContext Context { get; set; }

        public string GetSignatureDetailsString()
        {
            Signature signature = Image.Signature;

            string result =
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignatureLocation.ToString()) + ", " +
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignaturePosition.ToString()) + ", " +
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignatureLabelSize.ToString()) + ", " +
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignatureDelivery.ToString());
            return result;
            
        }
    }
}

AuthenticPhoto/Models/TotalPriceDetailsRowViewModel.cs
using AuthenticPhoto.Business.Abstract;
using AuthenticPhoto.Business.ProductTool;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuthenticPhoto.Models
{
    public class TotalPriceDetailsRowViewModel: ViewModelWithTranslations
    {
        public UploadedImage Image { get; set; }
        public string OrderID { get; set; }

        public string LanguageCode { get; set; }

        public string GetSignatureDetailsString()
        {
            Signature signature = Image.Signature;

            string result =
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignatureLocation.ToString()) + ", " +
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignaturePosition.ToString()) + ", " +
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignatureLabelSize.ToString()) + ", " +
            GetTranslation("ShowPreferences.Tabs.Signature." + signature.SignatureDelivery.ToString());
            return result;

        }
    }
}

AuthenticPhoto/Models/TotalPriceDetailsViewModel.cs
using AuthenticPhoto.Business.Abstract;
using AuthenticPhoto.Business.ProductTool;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuthenticPhoto.Models
{
    public class TotalPriceDetailsViewModel: ViewModelWithTranslations
    {
        public AuthenticOrder Order { get; set; }
        public bool CheckoutPageView { get; set; }

        public decimal CalculateVAT(decimal price)
        {
            return Math.Round(price * (decimal)0.21, 2);
        }
    }
}

AuthenticPhoto/Controllers/ProductToolController.cs
using AuthenticPhoto.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AuthenticPhoto.Business.ProductTool;
using System.Collections.Generic;
using AuthenticPhoto.Business.ProductTool.Entities;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using AuthenticPhoto.Business.Authentication;
using Microsoft.AspNet.Identity;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Umbraco.Web;
using AuthenticPhoto.ServiceReference1;
using Umbraco.Core.Models;
using System.Configuration;
using Newtonsoft.Json;
using Pulzonic.Multipartial;
using umbraco.MacroEngines;
using System.IO;
using AuthenticPhoto.Business.Abstract;
using System.Globalization;
using System.Threading;
using Umbraco.Web.Models;
using AuthenticPhoto.Business.AuthenticOrder;
using Umbraco.Web.Routing;

namespace AuthenticPhoto.Controllers
{

    public class ProductToolController : SurfaceController
    {
        private AuthenticUserManager _userManager;
        private DbConnector dbConnector;
        private DictionaryConnector dictionaryConnector;
        static string TOPROCESSDIR = ConfigurationManager.AppSettings["ToProcessFolder"];
        static string PROCESSEDDIR = ConfigurationManager.AppSettings["ProcessedFolder"];

        public AuthenticUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<AuthenticUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private IProductRepository productRepository;

        public ProductToolController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
            dbConnector = new DbConnector(this.productRepository);
            dictionaryConnector = new DictionaryConnector(System.Web.HttpContext.Current);
        }

        public AuthenticOrder CheckAuthenticOrder()
        {
            AuthenticOrder authenticOrder = GetAuthenticOrder();
            if (authenticOrder == null)
            {
                string orderID = Request.Cookies["authentic_orderid"] != null ? Request.Cookies["authentic_orderid"].Value : "";
                if (string.IsNullOrWhiteSpace(orderID))
                {
                    authenticOrder = dbConnector.AddOrder();
                    Response.Cookies.Add(createAuthenticOrderCookie(authenticOrder.OrderID));
                }
                else
                {
                    authenticOrder = dbConnector.GetOrder(orderID);
                    if (authenticOrder == null)
                    {
                        authenticOrder = dbConnector.AddOrder();
                        Response.Cookies.Add(createAuthenticOrderCookie(authenticOrder.OrderID));
                    }
                }
                SetAuthenticOrder(authenticOrder);
            }
            return authenticOrder;
        }

        private HttpCookie createAuthenticOrderCookie(string orderID)
        {
            HttpCookie orderCookie = new HttpCookie("authentic_orderid");
            orderCookie.Value = orderID;
            orderCookie.Expires = DateTime.Now.AddDays(30d);
            return orderCookie;
        }

        [HttpPost]
        public string GetImagesCountInOrder() // temp; basket should eventually show order count
        {
            CheckAuthenticOrder();
            return Convert.ToString(((AuthenticOrder)Session["AuthenticOrder"]).Images.Count);
        }

        //[HttpPost]
        //public string GetOrderCount()
        //{
        //    return Convert.ToString(((AuthenticOrder)Session["AuthenticOrder"]).Orders.Count);
        //}

        private IPublishedContent GetProductContentForBackofficeId(string backofficeID)
        {
            IPublishedContent productContent = null;
            foreach (IPublishedContent upf in GetUmbracoProductFamilies())
            {
                productContent = upf.Descendants().Where(d => d.DocumentTypeAlias == "Product").FirstOrDefault(p => p.GetPropertyValue("backofficeIdentifier").ToString().Equals(Convert.ToString(backofficeID)));
                if (productContent != null)
                {
                    break;
                }
            }
            return productContent;
        }

        private IPublishedContent GetProductContentForId(string id)
        {
            IPublishedContent productContent = null;
            foreach (IPublishedContent upf in GetUmbracoProductFamilies())
            {
                productContent = upf.Descendants().Where(d => d.DocumentTypeAlias == "Product").FirstOrDefault(p => p.Id == int.Parse(id));
                if (productContent != null)
                {
                    break;
                }
            }
            return productContent;
        }


        private string GetHtmlTemplateFromSession(string name)
        {
            if (Session["HtmlTemplates"] == null)
            {
                return "Exception: html templates not found in session";
            }
            else
            {
                Dictionary<string, string> htmlTemplates = (Dictionary<string, string>)Session["HtmlTemplates"];
                return htmlTemplates.ContainsKey(name) ? htmlTemplates[name] : "Exception: " + name + " not found in mail templates";
            }
        }

        private IPublishedContent[] GetUmbracoProductFamilies()
        {
            if (Session["UmbracoProductFamilies"] != null)
                return (IPublishedContent[])Session["UmbracoProductFamilies"];
            return null;
        }

        public ActionResult ProductInfo(string id)
        {
            bool renderGeneralInfo = (id == null || id.Trim().Equals("-1") || id.Trim().Equals("0"));

            if (!renderGeneralInfo)
            {
                IPublishedContent productContent = GetProductContentForBackofficeId(id);
                if (productContent == null)
                {
                    renderGeneralInfo = true;
                }
                else
                {
                    if(productContent.GetPropertyValue<string>("redirectsToAnotherProductPage").ToLower().Equals("true"))
                    {
                        productContent = GetProductContentForId(productContent.GetPropertyValue<string>("productIDToRedirectTo"));
                    }
                    var pcr = new PublishedContentRequest(new Uri(productContent.UrlAbsolute()), UmbracoContext.Current.RoutingContext);
                    pcr.Prepare();
                    UmbracoContext.PublishedContentRequest = pcr;
                    return PartialView("ProductInfo", productContent);
                }
            }
            if (renderGeneralInfo)
            {
                UmbracoHelper umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
                IPublishedContent uploaderInfoContent;
                switch (dictionaryConnector.GetUmbracoCulture())
                {
                    case DictionaryConnector.UmbracoCultureNL: uploaderInfoContent = umbracoHelper.TypedContent(1688); break;
                    case DictionaryConnector.UmbracoCultureFR: uploaderInfoContent = umbracoHelper.TypedContent(1678); break;
                    default: uploaderInfoContent = umbracoHelper.TypedContent(1679); break;
                }
                var pcr = new PublishedContentRequest(new Uri(uploaderInfoContent.UrlAbsolute()), UmbracoContext.Current.RoutingContext);
                pcr.Prepare();
                UmbracoContext.PublishedContentRequest = pcr;
                return PartialView("UploaderInfo", uploaderInfoContent);
            }
            return new EmptyResult();
        }

        public ActionResult SwitchImagePreferences(string imgID)
        {
            AuthenticOrder order = GetAuthenticOrder();
            UploadedImage img = GetAuthenticOrder().Images.FirstOrDefault(i => i.ID == imgID);
            MultipartialResult multipartialResult = new MultipartialResult(this);
            multipartialResult.AddView("Finishing", "col_prefs_finishing", new FinishingModel
            {
                OrderID = order.OrderID,
                Image = img,
                ProductFamilies = productRepository.GetProductFamiliesWithChildListing(),
                Dictionary = dictionaryConnector.GetDictionaryFor("Finishing"),
                LanguageCode = dictionaryConnector.GetUmbracoCulture()
            });
            return multipartialResult;
        }

        public ActionResult SelectProductCalc(string newProductId, string preferencesSet)
        {
            UploadedImage img = GetCalcImageFromSession();
            if(newProductId.Equals("0") || newProductId.Equals("-1"))
            {
                img.SelectedProduct = null;
                img.Preferences.Clear();
                img.ResetPrices();
            }
            else
            {
                img.SelectedProduct = productRepository.GetProductWithPopulatedChildren(Convert.ToInt32(newProductId));
                SetDefaults(img, false);
            }            
            return GetUIUpdateData(img, false);
        }

        public ActionResult SelectProduct(string imgID, string newProductId)
        {
            AuthenticOrder order = GetAuthenticOrder();
            UploadedImage img = GetAuthenticOrder().Images.FirstOrDefault(i => i.ID == imgID);
            if (newProductId.Equals("0") || newProductId.Equals("-1"))
            {
                img.SelectedProduct = null;
                img.Preferences.Clear();
                img.BorderWidth = 0;
                img.ResetPrices();
            }
            else
            {
                img.SelectedProduct = productRepository.GetProductWithPopulatedChildren(Convert.ToInt32(newProductId));
                SetDefaults(img, true);
            }
            return GetUIUpdateData(img, true);
        }

AuthenticPhoto/Views/ProductTool/Checkout.cshtml
@using System.Linq
@model AuthenticPhoto.Models.OrderStep3Model

<script type="text/javascript" src="@Url.Content("~/scripts/Checkout.js")"></script>
<link href="~/css/checkout.css" rel="stylesheet" />

@using (Ajax.BeginForm("PlaceOrder", "ProductTool",
                    new { },
                    new AjaxOptions { UpdateTargetId = "divThankyou" },
                    new { @id = "frmCheckout", role = "form" }))
{
    
    @Html.AntiForgeryToken()
    @Html.Hidden("copinfo");
    @Html.Hidden("tblorderhtml");
    @Html.Hidden("OrderID", Model.Order.OrderID);
    
    foreach (AuthenticPhoto.Business.ProductTool.TranslatedString translatedString in Model.GetTranslationsToRender())
    {
        @Html.Hidden("str" + translatedString.Key, translatedString.Value)
    }

    <div class="squareButton squareButtonYellow checkoutButton btnBack" value="Previous" style="float: right">
        <span class="glyphicon glyphicon-menu-left backIcon" aria-hidden="true"></span>
        <img src="/media/ajax-loader.gif" alt="loading" class="loader" />
        @Model.GetTranslation("Checkout.BackToPreferences")
    </div>

    bool requiredFieldsProvided = Model.User.HasRequiredFieldsFilledIn();

    <br/>

    <div class="checkoutColumn redBox" id="divManageUserAccount" data-useraddress-json="@Model.User.GetAddressJson()">
        <h3 style="display: inline-block">@Model.GetTranslation("Checkout.MyBillingInfo")</h3>

        @if (requiredFieldsProvided)
        {
            <label id="lblEditAccount" class="subtleLbl2" style="display: block; margin-left: 3px;">@Model.GetTranslation("Checkout.ModifyInfo")</label>
        }
        else
        {
            <label id="lblEditAccount" class="subtleLbl2" style="display: block; margin-left: 3px;">@Model.GetTranslation("Checkout.CompleteInfo")</label>
        }

        @Html.Action("Edit", "AAccount", new { user = Model.User, checkoutContext = true })

        @if (!requiredFieldsProvided)
        {
            <div style="float:right; position: relative; bottom: 32px; left: 13px;">
                <span id="btnCompletedAccount" class="btn btn-success squareButton squareButtonRed checkoutButton" value="Next">
                    @Model.GetTranslation("General.Next")
                    <span class="glyphicon glyphicon-menu-right nextIcon" aria-hidden="true"></span>
                </span>
            </div>
        }

    </div>

    <div class="checkoutColumn" id="divOrderPreferences">
        @if (requiredFieldsProvided)
        {
            @Html.Action("CheckoutOrderPreferences", "ProductTool", new { model = Model })
        }
    </div>
}

<div class="checkoutColumn" id="divCheckoutOverview">

    <h3 style="display: inline-block">@Model.GetTranslation("Checkout.Overview")</h3>
    <span class="glyphicon glyphicon-print print-icon"></span>
    <div id="phTotalPriceDetails">
        @Html.Action("TotalPriceDetails", "ProductTool", new { orderID = Model.Order.OrderID, checkoutPageView = true })
    </div>


</div>

AuthenticPhoto/Views/ProductTool/OrderStep1.cshtml
@model AuthenticPhoto.Models.OrderStep1Model

@Html.Hidden("OrderID", Model.AuthenticOrder.OrderID)

<div id="product-tool-wrapper">
    <div id="product-tool">
        <div id="product-tool-blanket" style="display: none">
            <img id="product-tool-blanket-loader" src="~/media/ajax-loader.gif" />
            <span id="product-tool-blanket-caption">                
                De producten worden opgehaald
            </span>            
        </div>
        <div id="uploader"></div>
    </div>
    <div id="info">
        @Html.Action("ProductInfo", "ProductTool", new { id = 0 })
    </div>
</div>

AuthenticPhoto/Views/ProductTool/OrderStep2.cshtml
@model AuthenticPhoto.Models.OrderStep2Model

@if (Model.AuthenticOrder.Images.Count > 0)
{
    @Html.Hidden("OrderID", Model.AuthenticOrder.OrderID)

    
    <div id="product-tool-wrapper">

        <div id="optionTypePickers">
        </div>

        <div id="product-tool">
            <div class="overlay" id="overlay_prefs">
                <span class="helper"></span>
                <div id="expl">
                    <div id="loadingText"></div>
                    <img src="/media/ajax-loader.gif" alt="loading" />
                </div>
            </div>
            
            <div id="btnMoreImages" type="button" class="squareButton squareButtonRed">
                <i class="fa fa-file-image-o" aria-hidden="true"></i>
                @Model.GetTranslation("ShowOrderForm.AddImages")&nbsp;&nbsp;
                <img src="/media/ajax-loader.gif" alt="loading" class="loader" />
            </div>

            <span class="timestamp-on-print">@DateTime.Now.ToString("dd/MM/yyyy HH:mm")</span>

            <div id="prefs-table">
                <div id="col_img" style="text-align: center">                    
                    @for (int i = 0; i < Model.AuthenticOrder.Images.Count; i++)
                    {
                        var uploadedImage = Model.AuthenticOrder.Images[i];
                        bool active = (uploadedImage.ID == Model.ActiveImageID);

                        <div id="prev_@uploadedImage.ID" data-imgid="@uploadedImage.ID" @(active ? "data-active" : "") style="display:@(active ? " " : " none")" class="prevParent">
                            <div class="prevWrapper">
                                <img src="@uploadedImage.GetThumbSource()" class="prev" data-imgid="@uploadedImage.ID" />
                            </div>
                            <h6 id="lbl_@uploadedImage.ID">@uploadedImage.GetFullName()</h6>
                        </div>
                    }

                    <div id="btnCheckout" type="button" value="Checkout" class="squareButton squareButtonRed">
                        @Model.GetTranslation("Preferences.FinishOrder")&nbsp;&nbsp;
                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                        <img src="/media/ajax-loader.gif" alt="loading" class="loader" />
                    </div>
                    
                </div>

                <div id="col_prefs">

                    <div id="col_prefs_thumbs">
                        @Html.Action("ThumbsList", "ProductTool", new { images = Model.AuthenticOrder.Images, activeImageID = Model.ActiveImageID })
                    </div>

                    <div id="col_prefs_finishing">
                        @Html.Action("Finishing", "ProductTool", new { orderID = Model.AuthenticOrder.OrderID, image = Model.GetActiveImage(), productFamilies = Model.ProductFamilies })
                    </div>

                </div>
            </div>

            <div id="totalPriceRecap" style="height: 0">
                @Html.Action("TotalPriceDetails", "ProductTool", new { orderID = Model.AuthenticOrder.OrderID })
            </div>



        </div>
        <div id="info">
            @Html.Action("ProductInfo", "ProductTool", new { id = Model.GetActiveProductID() })
        </div>
    </div>
}
else
{
    <script type="text/javascript">
        redirectToOrderStep(1);
    </script>
}

AuthenticPhoto/Views/ProductTool/OrderStep3.cshtml
@model AuthenticPhoto.Models.OrderStep3Model

@if (Model.AuthenticOrder.Images.Count > 0)
{
    @Html.Hidden("OrderID", Model.AuthenticOrder.OrderID)

    <div id="product-tool-wrapper">
        <div id="product-tool">
            @using (Ajax.BeginForm("PlaceOrder", "ProductTool",
                            new { },
                            new AjaxOptions { UpdateTargetId = "divThankyou" },
                            new { @id = "frmCheckout", role = "form" }))
            {

                @Html.AntiForgeryToken()
                @Html.Hidden("copinfo");
                @Html.Hidden("tblorderhtml");
                @Html.Hidden("OrderID", Model.AuthenticOrder.OrderID);

                foreach (AuthenticPhoto.Business.ProductTool.TranslatedString translatedString in Model.GetTranslationsToRender())
                {
                    @Html.Hidden("str" + translatedString.Key, translatedString.Value)
                }

                <div class="squareButton squareButtonYellow checkoutButton btnBack" value="Previous" style="float: right">
                    <span class="glyphicon glyphicon-menu-left backIcon" aria-hidden="true"></span>
                    <img src="/media/ajax-loader.gif" alt="loading" class="loader" />
                    @Model.GetTranslation("Checkout.BackToPreferences")
                </div>

                bool requiredFieldsProvided = Model.User.HasRequiredFieldsFilledIn();

                <br />

                <div class="checkoutColumn redBox" id="divManageUserAccount" data-useraddress-json="@Model.User.GetAddressJson()">
                    <h3 style="display: inline-block">@Model.GetTranslation("Checkout.MyBillingInfo")</h3>

                    @if (requiredFieldsProvided)
                    {
                        <label id="lblEditAccount" class="subtleLbl2" style="display: block; margin-left: 3px;">@Model.GetTranslation("Checkout.ModifyInfo")</label>
                    }
                    else
                    {
                        <label id="lblEditAccount" class="subtleLbl2" style="display: block; margin-left: 3px;">@Model.GetTranslation("Checkout.CompleteInfo")</label>
                    }

                    @Html.Action("Edit", "AAccount", new { user = Model.User, checkoutContext = true })

                    @if (!requiredFieldsProvided)
                    {
                        <div style="float:right; position: relative; bottom: 32px; left: 13px;">
                            <span id="btnCompletedAccount" class="btn btn-success squareButton squareButtonRed checkoutButton" value="Next">
                                @Model.GetTranslation("General.Next")
                                <span class="glyphicon glyphicon-menu-right nextIcon" aria-hidden="true"></span>
                            </span>
                        </div>
                    }

                </div>

                <div class="checkoutColumn" id="divOrderPreferences">
                    @if (requiredFieldsProvided)
                    {
                        @Html.Action("CheckoutOrderPreferences", "ProductTool", new { model = Model })
                    }
                </div>
            }

            <div class="checkoutColumn" id="divCheckoutOverview">

                <h3 style="display: inline-block">@Model.GetTranslation("Checkout.Overview")</h3>
                <span class="glyphicon glyphicon-print print-icon"></span>
                <div id="phTotalPriceDetails">
                    @Html.Action("TotalPriceDetails", "ProductTool", new { orderID = Model.AuthenticOrder.OrderID, checkoutPageView = true })
                </div>


            </div>
        </div>
    </div>
}
else
{
    <script type="text/javascript">
        redirectToOrderStep(1);
    </script>
}

AuthenticPhoto/Views/ProductTool/OrderSummary.cshtml
@using AuthenticPhoto.Business.ProductTool
@model AuthenticPhoto.Models.OrderSummaryViewModel

@{
    bool transport = Model.Order.Delivery != null && Model.Order.Delivery.Equals("transport");
    decimal totalPriceExclVatHandling = Model.Order.GetTotalPriceExclVatHandling();
    decimal vat = Model.CalculateVAT(totalPriceExclVatHandling, transport);
}

@Html.Hidden("VatValid", Model.VatValid)

<table>
    <tr>
        <td>@Model.GetTranslation("OrderSummary.TotalOrder")</td>
        <td class="alignright">@Formatting.PrintAsEuro(totalPriceExclVatHandling)</td>
    </tr>
    @if (transport)
    {
        <tr>
            <td>@Model.GetTranslation("OrderSummary.HandlingCharges")</td>
            <td class="alignright">@Model.GetTranslation("OrderSummary.ToConfirm")</td>
        </tr>
    }
    <tr>
        <td>@Model.GetTranslation("OrderSummary.VAT")</td>
        <td class="alignright">
            @if (transport)
            {
                @Model.GetTranslation("OrderSummary.ToConfirm")
            }
            else
            {
                @Formatting.PrintAsEuro(vat)
            }
        </td>
    </tr>
    <tr>
        <td>Totaal te betalen</td>
        <td class="alignright">
            @if (transport)
            {
                @Model.GetTranslation("OrderSummary.ToConfirm")
            }
            else
            {
                <strong class="yellow-highlight">
                @Formatting.PrintAsEuro(totalPriceExclVatHandling + vat)
                </strong>
            }
        </td>
    </tr>

</table>

AuthenticPhoto/Views/ProductTool/ProductInfo.cshtml
@model IPublishedContent
@{
    Layout = null;
}
<div class="row">
    @Html.GetGridHtml(Model, "grid", "ProductGrid")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        initHoverImages();
        $("#versies").hide();
    });
</script>

AuthenticPhoto/Views/ProductTool/ThumbsList.cshtml
@model AuthenticPhoto.Models.ThumbsListModel

<ul id="thumbs">
    @for (int i = 0; i < Model.UploadedImages.Count; i++)
            {
                var uploadedImage = Model.UploadedImages[i];
                bool active = uploadedImage.ID == Model.ActiveImageID;
                var thumbWidth = uploadedImage.ThumbWidth / 5;
                var thumbHeight = uploadedImage.ThumbHeight / 5;
                int readyForCheckout = uploadedImage.IsReadyForCheckout() ? 1 : 0;
                int productID = uploadedImage.SelectedProduct != null ? uploadedImage.SelectedProduct.ProductID : 0;

        <li data-imgid="@uploadedImage.ID" data-ready="@readyForCheckout">
            <img class="thumbStatusIcon thumbStatusWarning" src="/images/warning.png" style="display: none" title="@Model.GetTranslation("ShowPreferences.CompletePreferencesForImage")" />
            <img class="thumbStatusIcon thumbStatusComplete" src="/images/ok.png" style="display: @(readyForCheckout==0? "none":"block")" title="@Model.GetTranslation("ShowPreferences.PreferencesComplete")" />
            <div style="background-image: url(@uploadedImage.GetThumbSource()); background-size: @{@thumbWidth}px @{@thumbHeight}px; width: @{@thumbWidth}px; height: @{@thumbHeight}px;" data-imgid="@uploadedImage.ID" class="thumb @( active ? " thumbSelected": "" )" data-selectedproductid="@productID" data-isprocessed="@(uploadedImage.IsProcessed ? "1" : "0")">
                <a class="deleteImg">
                    <img src="~/media/close.png" alt="delete" />
                </a>
            </div>
        </li>
    }
</ul>

AuthenticPhoto/Views/ProductTool/TotalPriceDetailsCheckoutProductRow.cshtml
@using AuthenticPhoto.Business.ProductTool.Entities;
@model AuthenticPhoto.Models.CheckoutProductViewModel

<tr class="bottomBorderedRow">
    <td class="bottomBorderedCell" style="text-align:center">
        <label class="title-label">
            @Model.CheckoutProduct.Name[Model.LanguageCode]
        </label>       
    </td>
    <td>
        @Model.GetTranslation("ShowPreferences.Tabs.ImageData.Qty")
    </td>
    <td>
        <strong>@Model.CheckoutProduct.Qty</strong>
    </td>
    <td>
        <span class="price-label">
            @AuthenticPhoto.Business.ProductTool.Formatting.PrintAsEuro(Model.CheckoutProduct.Qty * Model.CheckoutProduct.Price)
        </span>
    </td>
</tr>